import React from 'react';
import { create } from 'zustand';

export const translations = {
  en: {
    home: "Home",
    newGames: "New Games",
    popularGames: "Popular Games",
    racingGames: "Racing Games",
    actionGames: "Action Games",
    sportsGames: "Sports Games",
    arcadeGames: "Arcade Games",
    logicGames: "Logic Games",
    numberGames: "Number Games",
    adventureGames: "Adventure Games",
    puzzleGames: "Puzzle Games",
    boardGames: "Board Games",
    aboutUs: "About Us",
    privacyPolicy: "Privacy Policy",
    termsCondition: "Terms & Condition",
    termsOfUse: "Terms of Use",
    searchPlaceholder: "Search games & categories...",
    featuredGames: "Featured Games",
    viewAll: "VIEW ALL",
    cookieTitle: "Cookie Policy",
    cookieText: "We care about your data, and we'd use cookies only to improve your experience.By using this website, you accpet out Cookies Policy. Learn More",
    accept: "Accept",
    reject: "Reject",
    chooseLanguage: "Choose the language",
    continue: "Continue",
    lastUpdated: "Last updated on 1/12/2021",
    aboutGamesato: "About Gamesato",
    startPlaying: "Start Playing",
    contactUs: "Contact Us",
    exploreGames: "Explore Games",
    favoriteGames: "Favorite Games",
    myFavoriteGames: "My Favorite Games",
    favoritesSubtitle: "Quick access to the H5 games you love playing most.",
    emptyFavorites: "Your list is empty",
    emptyFavoritesDesc: "Click the Heart icon on any game detail page to save it here.",
    aboutTitle: "About Gamesato",
    aboutIntro: "Welcome to Gamesato, your ultimate destination for high-quality, instant-play HTML5 H5 web games. Our mission is to deliver a fast, responsive, and engaging gaming experience right inside your browser—no downloads, installations, or sign-ups required to start playing.",
    aboutVisionTitle: "Our Core Vision",
    aboutVisionText: "We believe that playing web games should be frictionless. By optimizing game asset pipelines and using modern lightweight servers, we serve H5 game packages at maximum speeds, allowing gamers on any device (mobile, tablet, or desktop) to play instantly.",
    aboutDevTitle: "Developer Platform",
    aboutDevText: "Gamesato is also built to support the game developer community. We provide creators with developer-centric tools to upload ZIP game packages, monitor analytics, evaluate real-time play counts, and get in-depth user feedback metrics securely.",
    privacyTitle: "Privacy Policy",
    privacyIntro: "At Gamesato, one of our main priorities is the privacy of our visitors. This Privacy Policy document describes the types of information collected and recorded by Gamesato and how we use it to improve your experience.",
    privacySec1Title: "1. Information We Collect",
    privacySec1Text: "When you register or authenticate using OAuth providers (Google, Facebook, or Discord), we securely process basic details such as your display name, email address, and profile picture avatar. This information is solely used to personalize your account, preserve your game likes, and organize your favorite lists.",
    privacySec2Title: "2. Game Performance Analytics",
    privacySec2Text: "To maintain high portal speeds and curate the best games, we track gameplay metrics like play counts, duration, and user interaction signals. This data is aggregated anonymously and is never shared with third parties.",
    privacySec3Title: "3. Cookies and Storage Policy",
    privacySec3Text: "We use essential session tokens and local storage values to store your cookie consent preferences and keep you securely logged in. You can choose to accept or reject these cookies through our Cookie Policy popup settings.",
    termsTitle: "Terms of Use",
    termsIntro: "Welcome to Gamesato! These Terms of Use govern your access to and use of our website, services, and mobile applications. By accessing or using our portal, you agree to comply with and be bound by these terms.",
    termsSec1Title: "1. Agreement to Terms",
    termsSec1Text: "By accessing this website, we assume you accept these terms and conditions. Do not continue to use Gamesato if you do not agree to take all of the terms and conditions stated on this page.",
    termsSec2Title: "2. Intellectual Property License",
    termsSec2Text: "Unless otherwise stated, Gamesato and/or its licensors own the intellectual property rights for all material on Gamesato. All intellectual property rights are reserved. You must not copy, republish, sell, rent, or sub-license material from this portal.",
    termsSec3Title: "3. User Registration & Accounts",
    termsSec3Text: "Users must log in using supported OAuth providers (Google, Facebook, Discord) to save favorites, like games, or access admin-specific consoles. You are responsible for keeping your credentials confidential.",
    termsSec4Title: "4. Content Usage & Conduct",
    termsSec4Text: "Our portal allows you to play HTML5/H5 games. You agree to use the services solely for personal entertainment. Any attempt to reverse engineer, disrupt network servers, or hack the game platform is strictly prohibited.",
    termsSec5Title: "5. Disclaimer & Limitation of Liability",
    termsSec5Text: "The games and services on Gamesato are provided on an \"as is\" and \"as available\" basis without warranties of any kind. Gamesato shall not be liable for any indirect, consequential, or special liability arising out of or in connection with your use of this portal.",
    game_cut_the_candy_title: "Cut The Candy",
    game_cut_the_candy_desc: "Help the monster eat the candy! Cut the ropes, collect stars, and avoid obstacles in this delicious physics puzzle game.",
    game_head_soccer_2026_title: "Head Soccer 2026",
    game_head_soccer_2026_desc: "Get ready for the ultimate big-head football tournament of 2026. Kick, jump, and score goals to become the champion.",
    game_subway_riders_title: "Subway Riders",
    game_subway_riders_desc: "Dodge trains, run as fast as you can, collect gold coins, and escape from the inspector in this endless subway runner.",
    exitGame: "Exit Game",
    liveSession: "Live Session",
    playGame: "Play Game",
    likeGame: "Like Game",
    signInToLike: "Sign in to like",
    signInRequiredToLike: "Sign in is required to like games!",
    backToGames: "Back to Games",
    plays: "plays",
    deviceCompatibilityText: "Mobile, Tablet & Desktop",
    about: "About",
    playStation: "Play Station",
    instantGameplayDesc: "Instant gameplay on any modern web browser.",
      signIn: "Sign In",
    myFavorites: "My Favorites",
    logOut: "Log Out",
    logIn: "Log In",
    signUp: "Sign Up",
    welcomeBack: "Welcome Back!",
    joinGamesato: "Join Gamesato",
    loginDesc: "Log in to load your saved favorites, likes, and game statistics.",
    signupDesc: "Create an account to save favorites, like games, and track your gameplay statistics.",
    loginWithGoogle: "Log In with Google",
    signupWithGoogle: "Sign Up with Google",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    seoTitle: "Game Bite: Your Instant Gaming Hub",
    seoText1: "Experience the next generation of web-based gaming with Gamesato. We provide a curated selection of high-quality, free-to-play games run directly in your browser without any downloads or installations. Our platform is designed for clarity, allowing you to jump straight into the action across various genres.",
    seoWhyChooseTitle: "Why Choose Game Bite?",
    seoWhyChoose1: "✓ Instant access to 1000+ premium games",
    seoWhyChoose2: "✓ No installation or downloads required",
    seoWhyChoose3: "✓ Safe, ad-free feeling environment",
    seoMultiPlatformTitle: "Multi-Platform Play",
    seoMultiPlatformText: "Our games are optimized for all modern web browsers, ensuring seamless cross-device synchronization of your progress when you create a free account.",
    faqTitle: "Frequently Asked Questions",
    faq1Q: "What are the best free games on Gamesato?",
    faq1A: "We recommend starting with our Featured section, which currently highlights \"Super Cricket 2024\" and \"Nitro Velocity\". Our community ratings also highly recommend \"Dream Artist\" for puzzle enthusiasts.",
    faq2Q: "Can I play free games without installing anything?",
    faq2A: "Yes, all games on Gamesato are instant-play HTML5 games. They run directly in your web browser without requiring any downloads, installation, or configuration.",
    faq3Q: "Do I need to register to play?",
    faq3A: "No, registration is completely optional. You can play all games as a guest. However, creating a free account allows you to save your favorites, track play history, and customize your experience.",
  },
  fr: {
    home: "Accueil",
    newGames: "Nouveaux Jeux",
    popularGames: "Jeux Populaires",
    racingGames: "Jeux de Course",
    actionGames: "Jeux d'Action",
    sportsGames: "Jeux de Sport",
    arcadeGames: "Jeux d'Arcade",
    logicGames: "Jeux de Logique",
    numberGames: "Jeux de Chiffres",
    adventureGames: "Jeux d'Aventure",
    puzzleGames: "Jeux de Puzzle",
    boardGames: "Jeux de Société",
    aboutUs: "À propos de nous",
    privacyPolicy: "Politique de confidentialité",
    termsCondition: "Termes & Conditions",
    termsOfUse: "Conditions d'utilisation",
    searchPlaceholder: "Rechercher des jeux...",
    featuredGames: "Jeux en Vedette",
    viewAll: "VOIR TOUT",
    cookieTitle: "Politique relative aux cookies",
    cookieText: "Nous prenons soin de vos données et n'utilisons des cookies que pour améliorer votre expérience.",
    accept: "Accepter",
    reject: "Refuser",
    chooseLanguage: "Choisissez la langue",
    continue: "Continuer",
    lastUpdated: "Dernière mise à jour le 12/01/2021",
    aboutGamesato: "À propos de Gamesato",
    startPlaying: "Commencer à jouer",
    contactUs: "Contactez-nous",
    exploreGames: "Explorer les jeux",
    favoriteGames: "Mes Favoris",
      game_cut_the_candy_title: "Coupe le Bonbon",
    game_cut_the_candy_desc: "Aidez le monstre à manger le bonbon ! Coupez les cordes, ramassez des étoiles et évitez les obstacles dans ce délicieux jeu de puzzle physique.",
    game_head_soccer_2026_title: "Tête Football 2026",
    game_head_soccer_2026_desc: "Préparez-vous pour le tournoi de football de têtes ultime de 2026. Frappez, sautez et marquez des buts pour devenir le champion.",
    game_subway_riders_title: "Coureurs du Métro",
    game_subway_riders_desc: "Esquivez les trains, courez aussi vite que possible, collectez des pièces d'or et échappez à l'inspecteur dans ce coureur de métro sans fin.",
    exitGame: "Quitter le jeu",
    liveSession: "Session en direct",
    playGame: "Jouer au jeu",
    likeGame: "Aimer le jeu",
    signInToLike: "Connectez-vous pour aimer",
    signInRequiredToLike: "La connexion est requise pour aimer les jeux !",
    backToGames: "Retour aux jeux",
    plays: "parties",
    deviceCompatibilityText: "Mobile, Tablette & Ordinateur",
    about: "À propos",
    playStation: "Console de jeu",
    instantGameplayDesc: "Jeu instantané sur n'importe quel navigateur web moderne.",
    myFavoriteGames: "Mes jeux favoris",
    favoritesSubtitle: "Accès rapide aux jeux H5 que vous aimez le plus jouer.",
    emptyFavorites: "Votre liste est vide",
    emptyFavoritesDesc: "Cliquez sur l'icône de cœur sur n'importe quel jeu pour le sauvegarder ici.",
    signIn: "Se connecter",
    myFavorites: "Mes favoris",
    logOut: "Se déconnecter",
    logIn: "Se connecter",
    signUp: "S'inscrire",
    welcomeBack: "Bon retour !",
    joinGamesato: "Rejoindre Gamesato",
    loginDesc: "Connectez-vous pour charger vos favoris, mentions j'aime et statistiques de jeu sauvegardés.",
    signupDesc: "Créez un compte pour sauvegarder vos favoris, aimer des jeux et suivre vos statistiques de jeu.",
    loginWithGoogle: "Se connecter avec Google",
    signupWithGoogle: "S'inscrire avec Google",
    dontHaveAccount: "Vous n'avez pas de compte ?",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    seoTitle: "Game Bite : Votre plateforme de jeux instantanée",
    seoText1: "Découvrez la nouvelle génération de jeux sur le web avec Gamesato. Nous proposons une sélection de jeux gratuits de haute qualité, accessibles directement dans votre navigateur sans aucun téléchargement ni installation.",
    seoWhyChooseTitle: "Pourquoi choisir Game Bite ?",
    seoWhyChoose1: "✓ Accès instantané à plus de 1000 jeux premium",
    seoWhyChoose2: "✓ Pas de téléchargement ni d'installation",
    seoWhyChoose3: "✓ Environnement sécurisé et sans publicité",
    seoMultiPlatformTitle: "Jeu multiplateforme",
    seoMultiPlatformText: "Nos jeux sont optimisés pour tous les navigateurs web modernes, garantissant une synchronisation fluide de votre progression.",
    faqTitle: "Foire aux questions",
    faq1Q: "Quels sont les meilleurs jeux gratuits sur Gamesato ?",
    faq1A: "Nous vous recommandons de commencer par notre section En Vedette. Nos évaluations de la communauté recommandent également nos jeux de puzzle.",
    faq2Q: "Puis-je jouer à des jeux gratuits sans rien installer ?",
    faq2A: "Oui, tous les jeux sur Gamesato sont des jeux HTML5 instantanés qui s'exécutent directement dans votre navigateur.",
    faq3Q: "Dois-je m'enregistrer pour jouer ?",
    faq3A: "Non, l'enregistrement est totalement facultatif. Vous pouvez jouer à tous les jeux en tant qu'invité.",
      aboutTitle: "À propos de Gamesato",
    aboutIntro: "Bienvenue sur Gamesato, votre destination ultime pour des jeux web HTML5 H5 de haute qualité et à lecture instantanée. Notre mission est de vous offrir une expérience de jeu rapide, réactive et engageante directement dans votre navigateur, sans téléchargement, installation ou inscription requis.",
    aboutVisionTitle: "Notre vision principale",
    aboutVisionText: "Nous pensons que jouer à des jeux web doit être sans friction. En optimisant les flux de ressources de jeu et en utilisant des serveurs légers modernes, nous diffusons les paquets de jeux H5 à des vitesses maximales, permettant aux joueurs sur tout appareil de jouer instantanément.",
    aboutDevTitle: "Plateforme pour développeurs",
    aboutDevText: "Gamesato est également conçu pour soutenir la communauté des développeurs de jeux. Nous fournissons aux créateurs des outils axés sur les développeurs pour télécharger des paquets de jeux ZIP, surveiller les analyses et obtenir des commentaires détaillés des utilisateurs.",
    privacyTitle: "Politique de confidentialité",
    privacyIntro: "Chez Gamesato, l'une de nos principales priorités est la confidentialité de nos visiteurs. Ce document décrit les types d'informations collectées et enregistrées par Gamesato et comment nous les utilisons pour améliorer votre expérience.",
    privacySec1Title: "1. Informations que nous collectons",
    privacySec1Text: "Lorsque vous vous inscrivez ou vous authentifiez via des fournisseurs OAuth (Google, Facebook ou Discord), nous traitons en toute sécurité les informations de base telles que votre nom d'affichage, votre adresse e-mail et votre avatar. Ces informations sont uniquement utilisées pour personnaliser votre compte.",
    privacySec2Title: "2. Analyses de performance des jeux",
    privacySec2Text: "Pour maintenir des vitesses de portail élevées et sélectionner les meilleurs jeux, nous suivons anonymement les statistiques de jeu.",
    privacySec3Title: "3. Politique relative aux cookies",
    privacySec3Text: "Nous utilisons des jetons de session essentiels et des valeurs de stockage local pour stocker vos préférences de consentement aux cookies et vous maintenir connecté en toute sécurité.",
    termsTitle: "Conditions d'utilisation",
    termsIntro: "Bienvenue sur Gamesato ! Ces conditions d'utilisation régissent votre accès et votre utilisation de notre site Web, de nos services et de nos applications mobiles. En accédant à notre portail, vous acceptez de respecter ces conditions.",
    termsSec1Title: "1. Acceptation des conditions",
    termsSec1Text: "En accédant à ce site Web, nous supposons que vous acceptez ces conditions d'utilisation. Ne continuez pas à utiliser Gamesato si vous n'acceptez pas toutes les conditions énoncées sur cette page.",
    termsSec2Title: "2. Propriété intellectuelle",
    termsSec2Text: "Sauf indication contraire, Gamesato et/ou ses concédants de licence détiennent les droits de propriété intellectuelle de tout le matériel présent sur Gamesato. Tous les droits de propriété intellectuelle sont réservés.",
    termsSec3Title: "3. Comptes d'utilisateurs",
    termsSec3Text: "Les utilisateurs doivent se connecter en utilisant les fournisseurs OAuth pris en charge pour enregistrer des favoris, aimer des jeux ou accéder aux consoles d'administration.",
    termsSec4Title: "4. Utilisation du contenu et conduite",
    termsSec4Text: "Notre portail vous permet de jouer à des jeux HTML5/H5. Vous acceptez d'utiliser les services uniquement pour votre divertissement personnel. Toute tentative de rétro-ingénierie est strictement interdite.",
    termsSec5Title: "5. Limitation de responsabilité",
    termsSec5Text: "Les jeux et services sur Gamesato sont fournis « en l'état » sans aucune garantie d'aucune sorte. Gamesato ne sera pas responsable des dommages indirects ou consécutifs liés à l'utilisation du portail.",
  },
  de: {
    home: "Startseite",
    newGames: "Neue Spiele",
    popularGames: "Beliebte Spiele",
    racingGames: "Rennspiele",
    actionGames: "Actionspiele",
    sportsGames: "Sportspiele",
    arcadeGames: "Arcadespiele",
    logicGames: "Logikspiele",
    numberGames: "Zahlenspiele",
    adventureGames: "Abenteuerspiele",
    puzzleGames: "Puzzlespiele",
    boardGames: "Brettspiele",
    aboutUs: "Über uns",
    privacyPolicy: "Datenschutzrichtlinie",
    termsCondition: "Nutzungsbedingungen",
    termsOfUse: "Nutzungsbedingungen",
    searchPlaceholder: "Spiele suchen...",
    featuredGames: "Beliebte Spiele",
    viewAll: "ALLE ANZEIGEN",
    cookieTitle: "Cookie-Richtlinie",
    cookieText: "Wir kümmern uns um Ihre Daten und verwenden Cookies nur, um Ihre Erfahrung zu verbessern.",
    accept: "Akzeptieren",
    reject: "Ablehnen",
    chooseLanguage: "Sprache wählen",
    continue: "Weiter",
    lastUpdated: "Zuletzt aktualisiert am 12.01.2021",
    aboutGamesato: "Über Gamesato",
    startPlaying: "Jetzt spielen",
    contactUs: "Kontaktieren Sie uns",
    exploreGames: "Spiele durchsuchen",
    favoriteGames: "Meine Favoriten",
      game_cut_the_candy_title: "Schneide die Süßigkeit",
    game_cut_the_candy_desc: "Hilf dem Monster, die Süßigkeit zu essen! Schneide die Seile durch, sammle Sterne und weiche Hindernissen in diesem köstlichen Physik-Puzzlespiel aus.",
    game_head_soccer_2026_title: "Kopfball-Fußball 2026",
    game_head_soccer_2026_desc: "Mach dich bereit für das ultimative Großkopf-Fußballturnier 2026. Tritt, springe und schieße Tore, um Champion zu werden.",
    game_subway_riders_title: "U-Bahn Surfer",
    game_subway_riders_desc: "Weiche Zügen aus, renne so schnell du kannst, sammle Goldmünzen und entkomme dem Inspektor in diesem endlosen U-Bahn-Runner.",
    exitGame: "Spiel verlassen",
    liveSession: "Live-Sitzung",
    playGame: "Spiel spielen",
    likeGame: "Spiel liken",
    signInToLike: "Anmelden zum Liken",
    signInRequiredToLike: "Anmeldung ist erforderlich, um Spiele zu liken!",
    backToGames: "Zurück zu den Spielen",
    plays: "Spiele",
    deviceCompatibilityText: "Mobil, Tablet & Desktop",
    about: "Über",
    playStation: "Spielstation",
    instantGameplayDesc: "Sofortiges Gameplay auf jedem modernen Webbrowser.",
    myFavoriteGames: "Meine Lieblingsspiele",
    favoritesSubtitle: "Schneller Zugriff auf die H5-Spiele, die Sie am liebsten spielen.",
    emptyFavorites: "Ihre Liste ist leer",
    emptyFavoritesDesc: "Klicken Sie auf das Herz-Symbol auf einer Spielseite, um es hier zu speichern.",
    signIn: "Einloggen",
    myFavorites: "Meine Favoriten",
    logOut: "Ausloggen",
    logIn: "Einloggen",
    signUp: "Registrieren",
    welcomeBack: "Willkommen zurück!",
    joinGamesato: "Tritt Gamesato bei",
    loginDesc: "Melde dich an, um deine gespeicherten Favoriten, Likes und Spielstatistiken zu laden.",
    signupDesc: "Erstelle ein Konto, um Favoriten zu speichern, Spiele zu liken und deine Spielstatistiken zu verfolgen.",
    loginWithGoogle: "Mit Google anmelden",
    signupWithGoogle: "Mit Google registrieren",
    dontHaveAccount: "Hast du noch kein Konto?",
    alreadyHaveAccount: "Hast du bereits ein Konto?",
    seoTitle: "Game Bite: Ihre Plattform für Sofortspiele",
    seoText1: "Erleben Sie die nächste Generation des webbasierten Gamings mit Gamesato. Wir bieten eine kuratierte Auswahl an hochwertigen, kostenlos spielbaren Spielen, die direkt in Ihrem Browser ausgeführt werden.",
    seoWhyChooseTitle: "Warum Game Bite wählen?",
    seoWhyChoose1: "✓ Sofortiger Zugriff auf über 1000 Premium-Spiele",
    seoWhyChoose2: "✓ Keine Downloads oder Installationen erforderlich",
    seoWhyChoose3: "✓ Sichere, werbefreie Umgebung",
    seoMultiPlatformTitle: "Plattformübergreifendes Spielen",
    seoMultiPlatformText: "Unsere Spiele sind für alle modernen Webbrowser optimiert, um eine nahtlose Synchronisierung zu gewährleisten.",
    faqTitle: "Häufig gestellte Fragen",
    faq1Q: "Was sind die besten kostenlosen Spiele auf Gamesato?",
    faq1A: "Wir empfehlen, mit unserem Bereich 'Beliebt' zu beginnen. Auch unsere Puzzlespiele sind sehr zu empfehlen.",
    faq2Q: "Kann ich kostenlose Spiele ohne Installation spielen?",
    faq2A: "Ja, alle Spiele auf Gamesato sind HTML5-Sofortspiele, die direkt im Webbrowser ausgeführt werden.",
    faq3Q: "Muss ich mich registrieren, um zu spielen?",
    faq3A: "Nein, die Registrierung ist völlig optional. Sie können alle Spiele als Gast spielen.",
      aboutTitle: "Über Gamesato",
    aboutIntro: "Willkommen bei Gamesato, Ihrer ultimativen Plattform für hochwertige, sofort spielbare HTML5-H5-Webspiele. Unsere Mission ist es, ein schnelles, reaktionsschnelles und fesselndes Spielerlebnis direkt in Ihrem Browser zu bieten – ohne Downloads, Installationen oder Registrierungen.",
    aboutVisionTitle: "Unsere Kernvision",
    aboutVisionText: "Wir glauben, dass das Spielen von Webspielen reibungslos sein sollte. Durch die Optimierung von Spiel-Asset-Pipelines und den Einsatz moderner, leichtgewichtiger Server liefern wir H5-Spielpakete mit maximaler Geschwindigkeit aus, sodass Spieler auf jedem Gerät sofort spielen können.",
    aboutDevTitle: "Entwicklerplattform",
    aboutDevText: "Gamesato wurde auch zur Unterstützung der Spieleentwickler-Community entwickelt. Wir bieten Entwicklern Tools zum Hochladen von ZIP-Spielpaketen, zur Überwachung von Analysen und zum sicheren Einholen von detailliertem Feedback der Benutzer.",
    privacyTitle: "Datenschutzrichtlinie",
    privacyIntro: "Bei Gamesato ist die Privatsphäre unserer Besucher eine unserer Hauptprioritäten. Diese Datenschutzrichtlinie beschreibt die Arten von Informationen, die von Gamesato gesammelt und aufgezeichnet werden, und wie wir sie verwenden.",
    privacySec1Title: "1. Informationen, die wir sammeln",
    privacySec1Text: "Wenn Sie sich über OAuth-Anbieter (Google, Facebook oder Discord) registrieren oder authentifizieren, verarbeiten wir grundlegende Daten wie Ihren Anzeigenamen, Ihre E-Mail-Adresse und Ihr Profilbild sicher, um Ihr Profil zu personalisieren.",
    privacySec2Title: "2. Leistungsanalyse von Spielen",
    privacySec2Text: "Um eine hohe Portalgeschwindigkeit aufrechtzuerhalten und die besten Spiele auszuwählen, verfolgen wir Spielmetriken anonym.",
    privacySec3Title: "3. Cookies und Speicherrichtlinie",
    privacySec3Text: "Wir verwenden wichtige Sitzungstoken und lokale Speicherwerte, um Ihre Cookie-Zustimmungseinstellungen zu speichern und Sie sicher anzumelden.",
    termsTitle: "Nutzungsbedingungen",
    termsIntro: "Willkommen bei Gamesato! Diese Nutzungsbedingungen regeln Ihren Zugriff auf und Ihre Nutzung unserer Website, Dienste und mobilen Anwendungen. Mit dem Zugriff erklären Sie sich mit den Bedingungen einverstanden.",
    termsSec1Title: "1. Einverständnis mit den Bedingungen",
    termsSec1Text: "Durch den Zugriff auf diese Website gehen wir davon aus, dass Sie diese Nutzungsbedingungen akzeptieren. Nutzen Sie Gamesato nicht weiter, wenn Sie nicht mit allen Bedingungen auf dieser Seite einverstanden sind.",
    termsSec2Title: "2. Geistiges Eigentum",
    termsSec2Text: "Sofern nicht anders angegeben, besitzen Gamesato und/oder seine Lizenzgeber die geistigen Eigentumsrechte für alle Inhalte auf Gamesato. Alle geistigen Eigentumsrechte sind vorbehalten.",
    termsSec3Title: "3. Benutzerkonten",
    termsSec3Text: "Benutzer müssen sich mit unterstützten OAuth-Anbietern anmelden, um Favoriten zu speichern, Spiele zu liken oder auf Admin-Konsolen zuzugreifen.",
    termsSec4Title: "4. Inhaltsnutzung und Verhalten",
    termsSec4Text: "Unser Portal ermöglicht es Ihnen, HTML5/H5-Spiele zu spielen. Sie stimmen zu, die Dienste ausschließlich zur persönlichen Unterhaltung zu nutzen. Jeder Manipulationsversuch ist strengstens untersagt.",
    termsSec5Title: "5. Haftungsausschluss",
    termsSec5Text: "Die Spiele und Dienste auf Gamesato werden ohne Mängelgewähr bereitgestellt. Gamesato haftet nicht für indirekte Schäden, die aus der Nutzung des Portals entstehen.",
  },
  es: {
    home: "Inicio",
    newGames: "Juegos Nuevos",
    popularGames: "Juegos Populares",
    racingGames: "Juegos de Carreras",
    actionGames: "Juegos de Acción",
    sportsGames: "Juegos de Deportes",
    arcadeGames: "Juegos de Arcade",
    logicGames: "Juegos de Lógica",
    numberGames: "Juegos de Números",
    adventureGames: "Juegos de Aventura",
    puzzleGames: "Juegos de Rompecabezas",
    boardGames: "Juegos de Mesa",
    aboutUs: "Sobre nosotros",
    privacyPolicy: "Política de privacidad",
    termsCondition: "Términos y condiciones",
    termsOfUse: "Condiciones de uso",
    searchPlaceholder: "Buscar juegos...",
    featuredGames: "Juegos Destacados",
    viewAll: "VER TODO",
    cookieTitle: "Política de Cookies",
    cookieText: "Cuidamos sus datos y utilizamos cookies solo para mejorar su experiencia.",
    accept: "Aceptar",
    reject: "Rechazar",
    chooseLanguage: "Elige el idioma",
    continue: "Continuar",
    lastUpdated: "Última actualización el 12/01/2021",
    aboutGamesato: "Sobre Gamesato",
    startPlaying: "Comenzar a jugar",
    contactUs: "Contáctenos",
    exploreGames: "Explorar juegos",
    favoriteGames: "Mis favoritos",
      game_cut_the_candy_title: "Cortar el Caramelo",
    game_cut_the_candy_desc: "¡Ayuda al monstruo a comer el caramelo! Corta las cuerdas, recoge estrellas y evita los obstáculos en este delicioso juego de física.",
    game_head_soccer_2026_title: "Fútbol de Cabezas 2026",
    game_head_soccer_2026_desc: "Prepárate para el torneo de fútbol de cabezas más importante de 2026. Patea, salta y marca goles para convertirte en el campeón.",
    game_subway_riders_title: "Corredores del Metro",
    game_subway_riders_desc: "Esquiva trenes, corre tan rápido como puedas, recoge monedas de oro y escapa del inspector en este corredor de metro sin fin.",
    exitGame: "Salir del juego",
    liveSession: "Sesión en vivo",
    playGame: "Jugar juego",
    likeGame: "Me gusta",
    signInToLike: "Inicia sesión para dar me gusta",
    signInRequiredToLike: "¡Se requiere iniciar sesión para dar me gusta a los juegos!",
    backToGames: "Volver a juegos",
    plays: "reproducciones",
    deviceCompatibilityText: "Móvil, Tablet y Escritorio",
    about: "Acerca de",
    playStation: "Estación de juegos",
    instantGameplayDesc: "Juego instantáneo en cualquier navegador web moderno.",
    myFavoriteGames: "Mis juegos favoritos",
    favoritesSubtitle: "Acceso rápido a los juegos H5 que más te gusta jugar.",
    emptyFavorites: "Tu lista está vacía",
    emptyFavoritesDesc: "Haz clic en el icono de corazón en cualquier juego para guardarlo aquí.",
    signIn: "Iniciar Sesión",
    myFavorites: "Mis Favoritos",
    logOut: "Cerrar Sesión",
    logIn: "Iniciar Sesión",
    signUp: "Registrarse",
    welcomeBack: "¡Bienvenido de nuevo!",
    joinGamesato: "Únete a Gamesato",
    loginDesc: "Inicia sesión para cargar tus favoritos guardados, me gusta y estadísticas de juego.",
    signupDesc: "Crea una cuenta para guardar favoritos, dar me gusta a juegos y realizar un seguimiento de tus estadísticas.",
    loginWithGoogle: "Iniciar sesión con Google",
    signupWithGoogle: "Registrarse con Google",
    dontHaveAccount: "¿No tienes una cuenta?",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    seoTitle: "Game Bite: Tu centro de juegos instantáneos",
    seoText1: "Experimenta la próxima generación de juegos web con Gamesato. Ofrecemos una selección de juegos gratuitos de alta calidad directamente en tu navegador sin descargas ni instalaciones.",
    seoWhyChooseTitle: "¿Por qué elegir Game Bite?",
    seoWhyChoose1: "✓ Acceso instantáneo a más de 1000 juegos premium",
    seoWhyChoose2: "✓ Sin descargas ni instalaciones requeridas",
    seoWhyChoose3: "✓ Entorno seguro y sin anuncios molestos",
    seoMultiPlatformTitle: "Juego multiplataforma",
    seoMultiPlatformText: "Nuestros juegos están optimizados para todos los navegadores web modernos, lo que garantiza una sincronización perfecta.",
    faqTitle: "Preguntas frecuentes",
    faq1Q: "¿Cuáles son los mejores juegos gratuitos en Gamesato?",
    faq1A: "Recomendamos comenzar con nuestra sección Destacados. Nuestras clasificaciones de la comunidad también recomiendan los rompecabezas.",
    faq2Q: "¿Puedo jugar juegos gratis sin instalar nada?",
    faq2A: "Sí, todos los juegos en Gamesato son juegos instantáneos HTML5 que se ejecutan directamente en tu navegador.",
    faq3Q: "¿Necesito registrarme para jugar?",
    faq3A: "No, el registro es completamente opcional. Puedes jugar todos los juegos como invitado.",
      aboutTitle: "Sobre Gamesato",
    aboutIntro: "¡Bienvenido a Gamesato! Tu destino definitivo para jugar de forma instantánea a juegos web HTML5 H5 de alta calidad. Nuestra misión es ofrecer una experiencia de juego rápida, receptiva y atractiva directamente en tu navegador, sin descargas, instalaciones ni registros necesarios para empezar a jugar.",
    aboutVisionTitle: "Nuestra Visión Principal",
    aboutVisionText: "Creemos que jugar a juegos web debería ser sin fricciones. Al optimizar los pipelines de recursos y utilizar servidores ligeros modernos, servimos los paquetes de juegos H5 a la máxima velocidad, permitiendo a los jugadores de cualquier dispositivo jugar al instante.",
    aboutDevTitle: "Plataforma de Desarrolladores",
    aboutDevText: "Gamesato también está diseñado para apoyar a la comunidad de creadores de videojuegos. Proporcionamos herramientas para subir paquetes ZIP de juegos, monitorear análisis y evaluar el feedback de los usuarios de manera segura.",
    privacyTitle: "Política de Privacidad",
    privacyIntro: "En Gamesato, una de nuestras prioridades principales es la privacidad de nuestros visitantes. Este documento describe los tipos de información recopilada y registrada por Gamesato y cómo la utilizamos para mejorar tu experiencia.",
    privacySec1Title: "1. Información que Recopilamos",
    privacySec1Text: "Al registrarte o autenticarte a través de Google, Facebook o Discord, procesamos detalles básicos como tu nombre de usuario, correo electrónico y avatar. Esta información se usa únicamente para personalizar tu perfil, tus likes y tus listas de favoritos.",
    privacySec2Title: "2. Análisis de Rendimiento de los Juegos",
    privacySec2Text: "Para mantener la velocidad del portal y seleccionar los mejores juegos, registramos métricas de juego de forma anónima y agregada.",
    privacySec3Title: "3. Cookies y Almacenamiento Local",
    privacySec3Text: "Utilizamos cookies esenciales y almacenamiento local para mantener tu sesión activa y recordar tus preferencias de consentimiento de cookies a través del popup.",
    termsTitle: "Términos de Uso",
    termsIntro: "¡Bienvenido a Gamesato! Estos Términos de Uso rigen tu acceso y uso de nuestro portal de juegos. Al acceder a nuestro portal, aceptas cumplir y estar sujeto a estos términos.",
    termsSec1Title: "1. Aceptación de los Términos",
    termsSec1Text: "Al acceder a este sitio web, asumimos que aceptas estos términos y condiciones. Si no estás de acuerdo con alguna parte, no continúes usando Gamesato.",
    termsSec2Title: "2. Licencia de Propiedad Intelectual",
    termsSec2Text: "Gamesato y/o sus licenciantes poseen los derechos de propiedad intelectual de todo el material en el portal. Todos los derechos están reservados. No debes copiar, revender ni sublicenciar material de este sitio.",
    termsSec3Title: "3. Cuentas de Usuario y Registro",
    termsSec3Text: "Debes iniciar sesión utilizando proveedores de OAuth compatibles para guardar favoritos o acceder a consolas de administración.",
    termsSec4Title: "4. Conducta de los Usuarios",
    termsSec4Text: "Aceptas utilizar el servicio únicamente para entretenimiento personal. Queda estrictamente prohibido cualquier intento de piratear o desestabilizar la plataforma.",
    termsSec5Title: "5. Limitación de Responsabilidad",
    termsSec5Text: "Los servicios se proporcionan 'tal cual' sin garantías de ningún tipo. Gamesato no se hace responsable de daños indirectos surgidos del uso del portal.",
  },
  it: {
    home: "Home",
    newGames: "Nuovi Giochi",
    popularGames: "Giochi Popolari",
    racingGames: "Giochi di Corse",
    actionGames: "Giochi d'Azione",
    sportsGames: "Giochi di Sport",
    arcadeGames: "Giochi Arcade",
    logicGames: "Giochi di Logica",
    numberGames: "Giochi di Numeri",
    adventureGames: "Giochi di Avventura",
    puzzleGames: "Giochi di Puzzle",
    boardGames: "Giochi da Tavolo",
    aboutUs: "Chi siamo",
    privacyPolicy: "Informativa sulla privacy",
    termsCondition: "Termini e condizioni",
    termsOfUse: "Condizioni d'uso",
    searchPlaceholder: "Cerca giochi...",
    featuredGames: "Giochi in Evidenza",
    viewAll: "VEDI TUTTI",
    cookieTitle: "Politica sui Cookie",
    cookieText: "Ci prendiamo cura dei tuoi dati e utilizziamo i cookie solo per migliorare a tua esperienza.",
    accept: "Accetta",
    reject: "Rifiuta",
    chooseLanguage: "Scegli la lingua",
    continue: "Continua",
    lastUpdated: "Ultimo aggiornamento il 12/01/2021",
    aboutGamesato: "Informações sobre a Gamesato",
    startPlaying: "Inicia a jogar",
    contactUs: "Contate-nos",
    exploreGames: "Esplora i giochi",
    favoriteGames: "I miei preferiti",
      game_cut_the_candy_title: "Taglia la Caramella",
    game_cut_the_candy_desc: "Aiuta il mostro a mangiare la caramella! Taglia le corde, raccogli le stelle ed evita gli ostacoli in questo delizioso puzzle di fisica.",
    game_head_soccer_2026_title: "Calcio di Testa 2026",
    game_head_soccer_2026_desc: "Preparati per il torneo di calcio più importante del 2026. Calcia, salta e segna gol per diventare il campione.",
    game_subway_riders_title: "Corridori della Metropolitana",
    game_subway_riders_desc: "Schiva i treni, corri più veloce che puoi, raccogli monete d'oro e sfuggi all'ispettore in questo runner metropolitano senza fine.",
    exitGame: "Esci dal gioco",
    liveSession: "Sessione live",
    playGame: "Gioca",
    likeGame: "Mi piace",
    signInToLike: "Accedi per mettere mi piace",
    signInRequiredToLike: "L'accesso è richiesto per mettere mi piace ai giochi!",
    backToGames: "Torna ai giochi",
    plays: "partite",
    deviceCompatibilityText: "Mobile, Tablet & Desktop",
    about: "Informazioni",
    playStation: "Stazione di gioco",
    instantGameplayDesc: "Gioca all'istante su qualsiasi browser web moderno.",
    myFavoriteGames: "I miei giochi preferiti",
    favoritesSubtitle: "Accesso rapido ai giochi H5 che ami di più.",
    emptyFavorites: "La tua lista è vuota",
    emptyFavoritesDesc: "Clicca sull'icona del cuore in qualsiasi gioco per salvarlo qui.",
    signIn: "Accedi",
    myFavorites: "I miei Preferiti",
    logOut: "Esci",
    logIn: "Accedi",
    signUp: "Registrati",
    welcomeBack: "Bentornato!",
    joinGamesato: "Unisciti a Gamesato",
    loginDesc: "Accedi per caricare i tuoi preferiti salvati, i mi piace e le statistiche di gioco.",
    signupDesc: "Crea un account per salvare i preferiti, mettere mi piace ai giochi e tracciare le statistiche.",
    loginWithGoogle: "Accedi con Google",
    signupWithGoogle: "Registrati con Google",
    dontHaveAccount: "Non hai un account?",
    alreadyHaveAccount: "Hai già un account?",
    seoTitle: "Game Bite: Il tuo hub di gioco istantaneo",
    seoText1: "Prova la prossima generazione di giochi web con Gamesato. Offriamo una selezione curata di giochi gratuiti di alta qualità da avviare direttamente nel tuo browser.",
    seoWhyChooseTitle: "Perché scegliere Game Bite?",
    seoWhyChoose1: "✓ Accesso istantaneo a oltre 1000 giochi premium",
    seoWhyChoose2: "✓ Nessun download o installazione richiesti",
    seoWhyChoose3: "✓ Ambiente sicuro e senza pubblicità",
    seoMultiPlatformTitle: "Gioca su più piattaforme",
    seoMultiPlatformText: "I nostri giochi sono ottimizzati per tutti i browser moderni per garantire una sincronizzazione perfetta.",
    faqTitle: "Domande frequenti",
    faq1Q: "Quali sono i migliori giochi gratuiti su Gamesato?",
    faq1A: "Ti consigliamo di iniziare con la sezione In Evidenza. La nostra community consiglia molto anche i giochi di logica.",
    faq2Q: "Posso giocare ai giochi gratuiti senza installare nulla?",
    faq2A: "Sì, tutti i giochi su Gamesato sono giochi HTML5 istantanei che funzionano direttamente nel tuo browser.",
    faq3Q: "Devo registrarmi per giocare?",
    faq3A: "No, la registrazione è completamente opzionale. Puoi giocare a tutti i giochi come ospite.",
      aboutTitle: "Informazioni su Gamesato",
    aboutIntro: "Benvenuto su Gamesato, la tua destinazione finale per giochi web HTML5 H5 di alta qualità a riproduzione istantanea. La nostra missione è offrire un'esperienza di gioco veloce, reattiva e coinvolgente direttamente nel tuo browser, senza download o installazione richiesti.",
    aboutVisionTitle: "La nostra visione principale",
    aboutVisionText: "Riteniamo che il gioco online debba essere privo di ostacoli. Ottimizzando la distribuzione delle risorse ed utilizzando server leggeri e moderni, distribuiamo i pacchetti di giochi H5 alla massima velocità, consentendo l'avvio immediato su qualsiasi dispositivo.",
    aboutDevTitle: "Piattaforma per sviluppatori",
    aboutDevText: "Gamesato è progettato anche per supportare la community degli sviluppatori. Offriamo strumenti completi per caricare pacchetti di gioco in formato ZIP, monitorare le metriche di gioco in tempo reale e ottenere feedback.",
    privacyTitle: "Informativa sulla privacy",
    privacyIntro: "Su Gamesato, la privacy dei nostri utenti è di fondamentale importanza. Questo documento illustra i tipi di informazioni personali che raccogliamo e come le utilizziamo per offrirti un servizio migliore.",
    privacySec1Title: "1. Informazioni raccolte",
    privacySec1Text: "Quando accedi o ti registri utilizzando un provider OAuth (Google, Facebook o Discord), raccogliamo in modo sicuro le informazioni di base del profilo, come il nome utente e l'avatar, esclusivamente per personalizzare il tuo account.",
    privacySec2Title: "2. Statistiche di gioco",
    privacySec2Text: "Per garantire la velocità del portale e identificare i giochi migliori, monitoriamo le statistiche di utilizzo in forma completamente anonima.",
    privacySec3Title: "3. Cookie e archiviazione locale",
    privacySec3Text: "Utilizziamo cookie di sessione essenziali e variabili di local storage per memorizzare il tuo consenso all'uso dei cookie e mantenere attivo il login.",
    termsTitle: "Condizioni d'uso",
    termsIntro: "Benvenuto su Gamesato! Queste Condizioni d'uso regolano l'accesso e l'utilizzo del nostro sito web e dei relativi servizi. Utilizzando il portale, accetti queste condizioni.",
    termsSec1Title: "1. Accettazione delle condizioni",
    termsSec1Text: "Accedendo al sito web, si presume che l'utente accetti integralmente queste condizioni. Non continuare ad usare il portale se non sei d'accordo con i termini.",
    termsSec2Title: "2. Proprietà intellettuale",
    termsSec2Text: "Salvo diversa indicazione, Gamesato e/o i suoi concessori di licenza possiedono i diritti di proprietà intellettuale di tutto il materiale presente sul portale. Tutti i diritti sono riservati.",
    termsSec3Title: "3. Account utente",
    termsSec3Text: "Gli utenti devono autenticarsi tramite i provider supportati per salvare i propri preferiti e accedere all'area di amministrazione.",
    termsSec4Title: "4. Regole di condotta",
    termsSec4Text: "Il portale deve essere utilizzato esclusivamente per uso ricreativo personale. È vietato ogni tentativo di manomissione o attacco informatico.",
    termsSec5Title: "5. Limitazione di responsabilità",
    termsSec5Text: "I servizi sono offerti 'così come sono'. Gamesato non risponde di eventuali danni derivanti dall'utilizzo diretto o indiretto del portale.",
  },
  ar: {
    home: "الرئيسية",
    newGames: "ألعاب جديدة",
    popularGames: "ألعاب شعبية",
    racingGames: "ألعاب سباق",
    actionGames: "ألعاب حركة",
    sportsGames: "ألعاب رياضية",
    arcadeGames: "ألعاب آركيد",
    logicGames: "ألعاب ذكاء",
    numberGames: "ألعاب أرقام",
    adventureGames: "ألعاب مغامرات",
    puzzleGames: "ألعاب ألغاز",
    boardGames: "ألعاب لوحية",
    aboutUs: "معلومات عنا",
    privacyPolicy: "سياسة الخصوصية",
    termsCondition: "الشروط والأحكام",
    termsOfUse: "شروط الاستخدام",
    searchPlaceholder: "بحث عن ألعاب...",
    featuredGames: "ألعاب مميزة",
    viewAll: "عرض الكل",
    cookieTitle: "سياسة ملفات التعريف",
    cookieText: "نحن نهتم ببياناتك ونستخدم ملفات تعريف الارتباط فقط لتحسين تجربتك.",
    accept: "قبول",
    reject: "رفض",
    chooseLanguage: "اختر اللغة",
    continue: "متابعة",
    lastUpdated: "آخر تحديث في 12/01/2021",
    aboutGamesato: "حول غيم بايت",
    startPlaying: "ابدأ اللعب",
    contactUs: "اتصل بنا",
    exploreGames: "استكشف الألعاب",
    favoriteGames: "مفضلاتي",
      game_cut_the_candy_title: "اقطع الحلوى",
    game_cut_the_candy_desc: "ساعد الوحش على أكل الحلوى! اقطع الحبال، واجمع النجوم، وتجنب العقبات في لعبة ألغاز الفيزياء اللذيذة هذه.",
    game_head_soccer_2026_title: "كرة القدم بالرأس 2026",
    game_head_soccer_2026_desc: "استعد لبطولة كرة قدم الرأس الكبيرة لعام 2026. سدد وافز باللقب.",
    game_subway_riders_title: "ركاب مترو الأنفاق",
    game_subway_riders_desc: "تفادى القطارات، اركض بأسرع ما يمكن، اجمع العملات الذهبية، واهرب من المفتش.",
    exitGame: "الخروج من اللعبة",
    liveSession: "جلسة مباشرة",
    playGame: "العب الآن",
    likeGame: "اعجاب",
    signInToLike: "سجل الدخول للإعجاب",
    signInRequiredToLike: "تسجيل الدخول مطلوب للإعجاب بالألعاب!",
    backToGames: "العودة للألعاب",
    plays: "لعبة",
    deviceCompatibilityText: "الهاتف، الجهاز اللوحي والكمبيوتر",
    about: "حول",
    playStation: "محطة اللعب",
    instantGameplayDesc: "لعب فوري على أي متصفح ويب حديث.",
    myFavoriteGames: "ألعابي المفضلة",
    favoritesSubtitle: "وصول سريع إلى ألعاب H5 التي تحب لعبها أكثر.",
    emptyFavorites: "قائمتك فارغة",
    emptyFavoritesDesc: "انقر فوق رمز القلب في أي صفحة لعبة لحفظها هنا.",
    signIn: "تسجيل الدخول",
    myFavorites: "المفضلة",
    logOut: "تسجيل الخروج",
    logIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    welcomeBack: "مرحبًا بعودتك!",
    joinGamesato: "انضم إلى غيم بايت",
    loginDesc: "سجل الدخول لتحميل المفضلة المحفوظة والإعجابات وإحصاءات اللعب الخاصة بك.",
    signupDesc: "أنشئ حسابًا لحفظ المفضلة والإعجاب بالألعاب وتتبع إحصاءات اللعب الخاصة بك.",
    loginWithGoogle: "تسجيل الدخول باستخدام Google",
    signupWithGoogle: "إنشاء حساب باستخدام Google",
    dontHaveAccount: "ليس لديك حساب؟",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    seoTitle: "غيم بايت: مركز الألعاب الفورية الخاص بك",
    seoText1: "جرب الجيل القادم من ألعاب الويب مع غيم بايت. نحن نقدم مجموعة مختارة من الألعاب المجانية عالية الجودة التي تعمل مباشرة في متصفحك.",
    seoWhyChooseTitle: "لماذا تختار غيم بايت؟",
    seoWhyChoose1: "✓ وصول فوري لأكثر من 1000 لعبة مميزة",
    seoWhyChoose2: "✓ لا يتطلب أي تنزيل أو تثبيت",
    seoWhyChoose3: "✓ بيئة آمنة وخالية من الإعلانات",
    seoMultiPlatformTitle: "اللعب عبر منصات متعددة",
    seoMultiPlatformText: "ألعابنا محسّنة لجميع متصفحات الويب الحديثة لضمان مزامنة سلسة لتقدمك.",
    faqTitle: "الأسئلة الشائعة",
    faq1Q: "ما هي أفضل الألعاب المجانية على غيم بايت؟",
    faq1A: "نوصي بالبدء بقسم الألعاب المميزة لدينا. كما نوصي بألعاب الألغاز والذكاء.",
    faq2Q: "هل يمكنني اللعب بدون تثبيت أي شيء؟",
    faq2A: "نعم، جميع الألعاب على غيم بايت هي ألعاب HTML5 فورية تعمل مباشرة في متصفح الويب الخاص بك.",
    faq3Q: "هل أحتاج إلى التسجيل للعب؟",
    faq3A: "لا، التسجيل اختياري تمامًا. يمكنك لعب جميع الألعاب كضيف.",
      aboutTitle: "حول غيم بايت",
    aboutIntro: "مرحبًا بك في غيم بايت! وجهتك النهائية لألعاب الويب HTML5 H5 عالية الجودة واللعب الفوري. مهمتنا هي تقديم تجربة ألعاب سريعة ومتجاوبة وممتعة مباشرة داخل متصفحك دون الحاجة لتنزيل أو تثبيت.",
    aboutVisionTitle: "رؤيتنا الأساسية",
    aboutVisionText: "نعتقد أن لعب ألعاب الويب يجب أن يكون سلسًا. من خلال تحسين أصول الألعاب واستخدام خوادم خفيفة حديثة، نقدم ألعاب H5 بأقصى سرعة ممكنة لجميع الأجهزة.",
    aboutDevTitle: "منصة المطورين",
    aboutDevText: "تم تصميم غيم بايت أيضًا لدعم مجتمع مطوري الألعاب. نحن نوفر للمبدعين أدوات لرفع حزم الألعاب وملفات ZIP ومراقبة التحليلات بأمان.",
    privacyTitle: "سياسة الخصوصية",
    privacyIntro: "في غيم بايت، تعتبر خصوصية زوارنا من أهم أولوياتنا. تصف وثيقة سياسة الخصوصية هذه أنواع المعلومات التي نجمعها وكيف نستخدمها.",
    privacySec1Title: "1. المعلومات التي نجمعها",
    privacySec1Text: "عند التسجيل أو تسجيل الدخول باستخدام مزودي OAuth (Google أو Facebook أو Discord)، فإننا نعالج التفاصيل الأساسية مثل الاسم والبريد الإلكتروني والصورة لتخصيص حسابك.",
    privacySec2Title: "2. تحليلات أداء الألعاب",
    privacySec2Text: "للحفاظ على سرعة البوابة واختيار أفضل الألعاب، نتتبع إحصائيات اللعب بشكل مجهول بالكامل.",
    privacySec3Title: "3. سياسة ملفات تعريف الارتباط",
    privacySec3Text: "نستخدم ملفات تعريف الارتباط الأساسية والتخزين المحلي لحفظ تفضيلاتك والمحافظة على تسجيل دخولك بشكل آمن.",
    termsTitle: "شروط الاستخدام",
    termsIntro: "مرحبًا بك في غيم بايت! تحكم شروط الاستخدام هذه وصولك واستخدامك لموقعنا وخدماتنا. بالدخول للبوابة فإنك توافق على الالتزام بهذه الشروط.",
    termsSec1Title: "1. الموافقة على الشروط",
    termsSec1Text: "بدخولك إلى هذا الموقع، نفترض أنك تقبل شروط الاستخدام هذه بالكامل. لا تستمر في استخدام غيم بايت إذا كنت لا توافق عليها.",
    termsSec2Title: "2. ترخيص الملكية الفكرية",
    termsSec2Text: "ما لم ينص على خلاف ذلك، تمتلك غيم بايت و/أو مرخصوها حقوق الملكية الفكرية لجميع المواد المعروضة على البوابة.",
    termsSec3Title: "3. حسابات المستخدمين",
    termsSec3Text: "يجب على المستخدمين تسجيل الدخول باستخدام مزودي OAuth لحفظ المفضلة أو الوصول إلى لوحات الإدارة.",
    termsSec4Title: "4. السلوك والاستخدام المقبول",
    termsSec4Text: "أنت توافق على استخدام الخدمة للترفيه الشخصي فقط. يمنع منعا باتا أي محاولة لاختراق أو تخريب خوادم المنصة.",
    termsSec5Title: "5. حدود المسؤولية",
    termsSec5Text: "يتم تقديم الخدمات والألعاب على غيم بايت 'كما هي' دون أي ضمانات. لا تتحمل البوابة أي مسؤولية عن أضرار ناتجة عن الاستخدام.",
  },
  hi: {
    home: "मुख्य पृष्ठ",
    newGames: "नए खेल",
    popularGames: "लोकप्रिय खेल",
    racingGames: "दौड़ वाले खेल",
    actionGames: "ऐक्शन खेल",
    sportsGames: "खेलकूद",
    arcadeGames: "आर्केड खेल",
    logicGames: "तार्किक खेल",
    numberGames: "संख्या खेल",
    adventureGames: "रोमांचक खेल",
    puzzleGames: "पहेली खेल",
    boardGames: "बोर्ड खेल",
    aboutUs: "हमारे बारे में",
    privacyPolicy: "गोपनीयता नीति",
    termsCondition: "नियम और शर्तें",
    termsOfUse: "उपयोग की शर्तें",
    searchPlaceholder: "खेल खोजें...",
    featuredGames: "विशेष खेल",
    viewAll: "सभी देखें",
    cookieTitle: "कुकी नीति",
    cookieText: "हम आपके डेटा की देखभाल करते हैं और आपके अनुभव को बेहतर बनाने के लिए ही कुकीज़ का उपयोग करते हैं।",
    accept: "स्वीकार करें",
    reject: "अस्वीकार करें",
    chooseLanguage: "भाषा चुनें",
    continue: "जारी रखें",
    lastUpdated: "अंतिम अपडेट 1/12/2021 को",
    aboutGamesato: "गेमबाइट के बारे में",
    startPlaying: "खेलना शुरू करें",
    contactUs: "हमसे संपर्क करें",
    exploreGames: "खेलों का अन्वेषण करें",
    favoriteGames: "मेरे पसंदीदा",
    myFavoriteGames: "मेरे पसंदीदा खेल",
    favoritesSubtitle: "उन H5 खेलों तक त्वरित पहुँच जिन्हें आप खेलना सबसे अधिक पसंद करते हैं।",
    emptyFavorites: "आपकी सूची खाली है",
    emptyFavoritesDesc: "इसे यहाँ सहेजने के लिए किसी भी खेल विवरण पृष्ठ पर दिल (Heart) आइकन पर क्लिक करें।",
    aboutTitle: "गेमबाइट के बारे में",
    aboutIntro: "गेमबाइट में आपका स्वागत है, जो कि उच्च गुणवत्ता वाले तुरंत खेलने योग्य HTML5 H5 वेब गेम्स के लिए आपका अंतिम गंतव्य है। हमारा मिशन सीधे आपके ब्राउज़र के भीतर सबसे तेज़, सबसे प्रतिक्रियाशील गेमिंग अनुभव प्रदान करना है - खेलने के लिए किसी डाउनलोड या इंस्टॉलेशन की आवश्यकता नहीं है।",
    aboutVisionTitle: "हमारा मुख्य दृष्टिकोण",
    aboutVisionText: "हमारा मानना है कि वेब गेम खेलना पूरी तरह से आसान होना चाहिए। गेम परिसंपत्तियों को अनुकूलित करके और आधुनिक हल्के सर्वरों का उपयोग करके, हम H5 गेम पैकेजों को अधिकतम गति पर परोसते हैं, जिससे किसी भी डिवाइस (मोबाइल, टैबलेट या डेस्कटॉप) पर गेमर्स तुरंत खेल सकते हैं।",
    aboutDevTitle: "डेवलपर प्लेटफॉर्म",
    aboutDevText: "गेमबाइट डेवलपर समुदाय का समर्थन करने के लिए भी बनाया गया है। हम रचनाकारों को ज़िप गेम पैकेज अपलोड करने, एनालिटिक्स की निगरानी करने, वास्तविक समय में खेलने की संख्या का मूल्यांकन करने और गहन उपयोगकर्ता फीडबैक प्राप्त करने के लिए डेवलपर-केंद्रित उपकरण प्रदान करते हैं।",
    privacyTitle: "गोपनीयता नीति",
    privacyIntro: "गेमबाइट पर, हमारी मुख्य प्राथमिकताओं में से एक हमारे आगंतुकों की गोपनीयता है। यह गोपनीयता नीति दस्तावेज़ विभिन्न प्रकार की एकत्रित और रिकॉर्ड की गई जानकारी का विवरण देता है।",
    privacySec1Title: "1. एकत्रित जानकारी",
    privacySec1Text: "जब आप Google, Facebook या Discord के माध्यम से लॉग इन करते हैं, तो हम आपका नाम, ईमेल और प्रोफ़ाइल चित्र सुरक्षित रूप से संसाधित करते हैं। इसका उपयोग केवल आपके पसंदीदा खेलों को सहेजने और प्रोफ़ाइल को अनुकूलित करने के लिए किया जाता है।",
    privacySec2Title: "2. खेल प्रदर्शन एनालिटिक्स",
    privacySec2Text: "पोर्टल की गति बनाए रखने और बेहतरीन खेलों को चुनने के लिए, हम खेलने की संख्या और समय को गुमनाम रूप से ट्रैक करते हैं।",
    privacySec3Title: "3. कुकीज़ नीति",
    privacySec3Text: "हम आपको सुरक्षित रूप से लॉग इन रखने और आपकी कुकी प्राथमिकताओं को याद रखने के लिए कुकीज़ का उपयोग करते हैं।",
    termsTitle: "उपयोग की शर्तें",
    termsIntro: "गेमबाइट में आपका स्वागत है! ये उपयोग की शर्तें हमारी वेबसाइट और सेवाओं के आपके उपयोग को नियंत्रित करती हैं। गेमबाइट का उपयोग करके, आप इन शर्तों से सहमत होते हैं।",
    termsSec1Title: "1. शर्तों की स्वीकृति",
    termsSec1Text: "इस वेबसाइट तक पहुँचने पर, हम यह मान लेते हैं कि आप इन शर्तों को स्वीकार करते हैं। यदि आप इन सभी शर्तों से सहमत नहीं हैं, तो खेल खेलना जारी न रखें।",
    termsSec2Title: "2. बौद्धिक संपदा लाइसेंस",
    termsSec2Text: "जब तक अन्यथा न कहा जाए, गेमबाइट और/या इसके लाइसेंसकर्ता गेमबाइट पर सभी सामग्रियों के बौद्धिक संपदा अधिकारों के स्वामी हैं।",
    termsSec3Title: "3. उपयोगकर्ता खाते और जिम्मेदारियां",
    termsSec3Text: "पसंदीदा खेलों को सहेजने और ट्रैक करने के लिए समर्थित लॉगिन का उपयोग करें। आप अपने खाते की गोपनीयता बनाए रखने के लिए जिम्मेदार हैं।",
    termsSec4Title: "4. निषिद्ध आचरण",
    termsSec4Text: "आप इस पोर्टल का उपयोग केवल मनोरंजन के लिए करने की सहमति देते हैं। किसी भी प्रकार की हैकिंग या अनधिकृत स्क्रैपिंग पूरी तरह से प्रतिबंधित है।",
    termsSec5Title: "5. देयता की सीमा",
    termsSec5Text: "गेमबाइट पर सेवाएं 'जैसी हैं' वैसे ही प्रदान की जाती हैं। गेमबाइट किसी भी अप्रत्यक्ष या परिणामी देयता के लिए उत्तरदायी नहीं होगा।",
    game_cut_the_candy_title: "कैंडी काटो",
    game_cut_the_candy_desc: "राक्षस को कैंडी खाने में मदद करें! रस्सियों को काटें, सितारों को इकट्ठा करें, और इस भौतिक पहेली खेल में बाधाओं से बचें।",
    game_head_soccer_2026_title: "हेड सॉकर 2026",
    game_head_soccer_2026_desc: "2026 के अंतिम बड़े सिर वाले फुटबॉल टूर्नामेंट के लिए तैयार हो जाएं। किक मारें, कूदें और गोल करके चैंपियन बनें।",
    game_subway_riders_title: "सबवे राइडर्स",
    game_subway_riders_desc: "ट्रेनों से बचें, जितना हो सके उतनी तेजी से दौड़ें, सोने के सिक्के एकत्र करें, और इंस्पेक्टर से दूर भागें।",
    exitGame: "खेल से बाहर निकलें",
    liveSession: "सजीव सत्र",
    playGame: "खेल खेलें",
    likeGame: "पसंद करें",
    signInToLike: "पसंद करने के लिए लॉग इन करें",
    signInRequiredToLike: "खेलों को पसंद करने के लिए लॉगिन आवश्यक है!",
    backToGames: "खेलों पर वापस जाएं",
    plays: "बार खेला गया",
    deviceCompatibilityText: "मोबाइल, टैबलेट और डेस्कटॉप",
    about: "के बारे में",
    playStation: "प्ले स्टेशन",
    instantGameplayDesc: "किसी भी आधुनिक वेब ब्राउज़र पर तुरंत खेलें।",
      signIn: "लॉगिन करें",
    myFavorites: "मेरे पसंदीदा",
    logOut: "लॉग आउट",
    logIn: "लॉग इन करें",
    signUp: "साइन अप करें",
    welcomeBack: "वापसी पर स्वागत है!",
    joinGamesato: "गेमबाइट से जुड़ें",
    loginDesc: "अपने सहेजे गए पसंदीदा, पसंद और गेम आंकड़े लोड करने के लिए लॉगिन करें।",
    signupDesc: "पसंदीदा को सहेजने, गेम पसंद करने और अपने गेमप्ले आंकड़ों को ट्रैक करने के लिए एक खाता बनाएं।",
    loginWithGoogle: "Google के साथ लॉगिन करें",
    signupWithGoogle: "Google के साथ साइन अप करें",
    dontHaveAccount: "खाता नहीं है?",
    alreadyHaveAccount: "पहले से ही एक खाता है?",
    seoTitle: "गेमबाइट: आपका त्वरित गेमिंग हब",
    seoText1: "गेमबाइट के साथ वेब-आधारित गेमिंग की अगली पीढ़ी का अनुभव करें। हम सीधे आपके ब्राउज़र में चलने वाले उच्च-गुणवत्ता वाले, मुफ्त गेम प्रदान करते हैं।",
    seoWhyChooseTitle: "गेमबाइट क्यों चुनें?",
    seoWhyChoose1: "✓ 1000+ प्रीमियम गेम्स तक त्वरित पहुंच",
    seoWhyChoose2: "✓ कोई डाउनलोड या इंस्टॉलेशन आवश्यक नहीं",
    seoWhyChoose3: "✓ सुरक्षित और विज्ञापन-मुक्त वातावरण",
    seoMultiPlatformTitle: "मल्टी-प्लेटफ़ॉर्म प्ले",
    seoMultiPlatformText: "हमारे गेम सभी आधुनिक वेब ब्राउज़रों के लिए अनुकूलित हैं, जो आपकी प्रगति के सहज सिंक्रनाइज़ेशन को सुनिश्चित करते हैं।",
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    faq1Q: "गेमबाइट पर सबसे अच्छे मुफ्त गेम कौन से हैं?",
    faq1A: "हम अपने विशेष गेम अनुभाग से शुरुआत करने की सलाह देते हैं। हमारे पहेली गेम भी काफी लोकप्रिय हैं।",
    faq2Q: "क्या मैं बिना कुछ इंस्टॉल किए मुफ्त गेम खेल सकता हूँ?",
    faq2A: "हाँ, गेमबाइट पर सभी गेम त्वरित-खेलने वाले HTML5 गेम हैं जो सीधे आपके ब्राउज़र में चलते हैं।",
    faq3Q: "क्या मुझे खेलने के लिए पंजीकरण करने की आवश्यकता है?",
    faq3A: "नहीं, पंजीकरण पूरी तरह से वैकल्पिक है। आप अतिथि के रूप में सभी गेम खेल सकते हैं।",
  },
  ja: {
    home: "ホーム",
    newGames: "新作ゲーム",
    popularGames: "人気ゲーム",
    racingGames: "レースゲーム",
    actionGames: "アクションゲーム",
    sportsGames: "スポーツゲーム",
    arcadeGames: "アーケードゲーム",
    logicGames: "パズルゲーム",
    numberGames: "数字ゲーム",
    adventureGames: "アドベンチャー",
    puzzleGames: "パズル",
    boardGames: "ボードゲーム",
    aboutUs: "運営会社",
    privacyPolicy: "プライバシーポリシー",
    termsCondition: "利用規約",
    termsOfUse: "利用規約",
    searchPlaceholder: "ゲームを検索...",
    featuredGames: "おすすめゲーム",
    viewAll: "すべて表示",
    cookieTitle: "クッキーポリシー",
    cookieText: "私たちはあなたのデータを大切にし、体験を向上させるためにのみクッキーを使用します。",
    accept: "同意する",
    reject: "拒否する",
    chooseLanguage: "言語を選択してください",
    continue: "続行する",
    lastUpdated: "最終更新日: 2021/01/12",
    aboutGamesato: "Gamesatoについて",
    startPlaying: "プレイを開始",
    contactUs: "お問い合わせ",
    exploreGames: "ゲームを探索",
    favoriteGames: "お気に入り",
      game_cut_the_candy_title: "キャンディカット",
    game_cut_the_candy_desc: "モンスターがキャンディを食べるのを手伝おう！ロープをカットし、星を集め、障害物を避ける物理パズルゲーム。",
    game_head_soccer_2026_title: "ヘッドサッカー2026",
    game_head_soccer_2026_desc: "2026年の究極のデカ頭サッカー大会に備えよう。蹴って、跳んで、ゴールを決めてチャンピオンになろう。",
    game_subway_riders_title: "サブウェイライダーズ",
    game_subway_riders_desc: "電車を避け、できるだけ速く走り、金貨を集めてインスペクターから逃げ切ろう。",
    exitGame: "ゲームを終了する",
    liveSession: "ライブセッション",
    playGame: "プレイを開始",
    likeGame: "お気に入りに追加",
    signInToLike: "ログインしてお気に入りに追加",
    signInRequiredToLike: "ゲームをお気に入りに追加するにはログインが必要です！",
    backToGames: "ゲーム一覧に戻る",
    plays: "回プレイされました",
    deviceCompatibilityText: "スマホ、タブレット、PC対応",
    about: "詳細",
    playStation: "プレイステーション",
    instantGameplayDesc: "最新のブラウザですぐに遊べます。ダウンロード不要。",
    myFavoriteGames: "お気に入りゲーム",
    favoritesSubtitle: "お気に入りのゲームに素早くアクセスできます。",
    emptyFavorites: "リストは空です",
    emptyFavoritesDesc: "ゲーム詳細ページでハートアイコンをクリックするとここに保存されます。",
    signIn: "ログイン",
    myFavorites: "お気に入り一覧",
    logOut: "ログアウト",
    logIn: "ログイン",
    signUp: "新規登録",
    welcomeBack: "おかえりなさい！",
    joinGamesato: "Gamesatoに参加する",
    loginDesc: "ログインして、保存したお気に入りやプレイ統計を読み込みます。",
    signupDesc: "アカウントを作成してお気に入りの保存やプレイ統計の追跡を行いましょう。",
    loginWithGoogle: "Googleでログイン",
    signupWithGoogle: "Googleで登録",
    dontHaveAccount: "アカウントをお持ちでないですか？",
    alreadyHaveAccount: "既にアカウントをお持ちですか？",
    seoTitle: "Game Bite: インスタントゲームハブ",
    seoText1: "Gamesatoで次世代のウェブゲームを体験。ダウンロードやインストール不要で、ブラウザですぐに遊べる高品質な無料ゲームを提供しています。",
    seoWhyChooseTitle: "Game Biteが選ばれる理由",
    seoWhyChoose1: "✓ 1000以上のプレミアムゲームに即アクセス",
    seoWhyChoose2: "✓ インストールやダウンロードは一切不要",
    seoWhyChoose3: "✓ 安全で広告に邪魔されない環境",
    seoMultiPlatformTitle: "マルチプラットフォーム対応",
    seoMultiPlatformText: "当サイトのゲームはすべての最新ブラウザに最適化されており、デバイス間で進行状況が同期されます。",
    faqTitle: "よくある質問",
    faq1Q: "Gamesatoで一番おすすめの無料ゲームは？",
    faq1A: "おすすめゲームセクションから始めることをお勧めします。パズルゲームも非常に人気があります。",
    faq2Q: "インストールなしで無料ゲームをプレイできますか？",
    faq2A: "はい、Gamesatoのゲームはすべてブラウザ上で直接起動するHTML5ゲームです。",
    faq3Q: "プレイするには会員登録が必要ですか？",
    faq3A: "いいえ、登録は完全に任意です。ゲストとしてすべてのゲームをプレイできます。",
      aboutTitle: "Gamesatoについて",
    aboutIntro: "高品質でダウンロード不要のHTML5/H5ウェブゲームがすぐに遊べる「Gamesato」へようこそ！私たちの使命は、ブラウザ上で軽快、高速、かつ魅力的なゲーム体験を提供することです。会員登録も不要で、手軽にプレイを開始できます。",
    aboutVisionTitle: "私たちのビジョン",
    aboutVisionText: "私たちはウェブゲームのプレイが誰にとっても快適であるべきだと信じています。データ構造を最適化し、高性能サーバーを利用することで、H5ゲームを素早く配信し、モバイル、タブレット、PCのあらゆる環境で瞬時にロードされます。",
    aboutDevTitle: "開発者向けプラットフォーム",
    aboutDevText: "Gamesatoは、インディーゲームデベロッパーのサポートも視野に入れて構築されています。ZIP形式でのゲームのアップロード機能や統計アナリティクスの提供、リアルタイムのプレイ動向の追跡を安全に行える機能を提供しています。",
    privacyTitle: "プライバシーポリシー",
    privacyIntro: "Gamesatoでは、訪問者のプライバシーの保護を非常に重視しています。このプライバシーポリシー文書には、Gamesatoが収集する情報の種類と、ユーザー体験向上のための利用方法が記載されています。",
    privacySec1Title: "1. 収集する情報について",
    privacySec1Text: "Google、Facebook、またはDiscordなどの外部OAuth認証を利用してログインされた場合、アカウントのパーソナライズ、お気に入りの保存のために、ユーザー名やメールアドレス、プロフィール写真を安全に保存します。",
    privacySec2Title: "2. パフォーマンス統計",
    privacySec2Text: "ポータル全体の利便性の向上や人気のゲームを判断するため、個人の特定につながらない形でゲームのプレイ回数や時間を追跡します。",
    privacySec3Title: "3. クッキーとストレージ",
    privacySec3Text: "ユーザーのログイン状態の保持や、クッキー同意設定の記録のために、必須クッキーおよびローカルストレージ情報を使用します。",
    termsTitle: "利用規約",
    termsIntro: "Gamesatoへようこそ！この利用規約は、当ウェブサイトおよび提供されるサービス、モバイルアプリの利用に関する規約を定めたものです。サービスを利用することで、規約に同意したとみなされます。",
    termsSec1Title: "1. 規約の承諾",
    termsSec1Text: "本サイトにアクセスすることで、利用者は利用規約に同意したものとみなされます。規約のいずれかの条項に同意できない場合は、利用を中止してください。",
    termsSec2Title: "2. 知的財産権",
    termsSec2Text: "特段の記載がない限り、Gamesatoおよびそのライセンサーが、Gamesato内のすべてのコンテンツに関する知的財産権を保有しています。無断転載等は禁止されています。",
    termsSec3Title: "3. ユーザーアカウント",
    termsSec3Text: "お気に入り登録やいいね機能、管理画面へのアクセスを行うには、外部OAuth認証を利用したログインが必要です。",
    termsSec4Title: "4. 禁止事項",
    termsSec4Text: "利用者は本サービスを個人の娯楽目的でのみ利用することに同意します。サーバーへの不正アクセス、リバースエンジニアリング、チート行為は厳重に禁止します。",
    termsSec5Title: "5. 免責事項",
    termsSec5Text: "本サービスは現状有姿で提供され、一切の保証を行いません。サービスの利用に起因するいかなる損害についても、Gamesatoは責任を負いません。",
  },
  pt: {
    home: "Início",
    newGames: "Novos Jogos",
    popularGames: "Jogos Populares",
    racingGames: "Jogos de Corrida",
    actionGames: "Jogos de Ação",
    sportsGames: "Jogos de Esporte",
    arcadeGames: "Jogos Arcade",
    logicGames: "Jogos de Lógica",
    numberGames: "Jogos de Números",
    adventureGames: "Jogos de Aventura",
    puzzleGames: "Quebra-cabeças",
    boardGames: "Jogos de Tabuleiro",
    aboutUs: "Sobre nós",
    privacyPolicy: "Política de privacidade",
    termsCondition: "Termos e condições",
    termsOfUse: "Termos de uso",
    searchPlaceholder: "Buscar jogos...",
    featuredGames: "Jogos em Destaque",
    viewAll: "VER TODOS",
    cookieTitle: "Política de Cookies",
    cookieText: "Cuidamos dos seus dados e usamos cookies apenas para melhorar a sua experiência.",
    accept: "Aceitar",
    reject: "Rejeitar",
    chooseLanguage: "Escolha o idioma",
    continue: "Continuar",
    lastUpdated: "Última atualização em 12/01/2021",
    aboutGamesato: "Sobre o Gamesato",
    startPlaying: "Começar a jogar",
    contactUs: "Contate-nos",
    exploreGames: "Explorar jogos",
    favoriteGames: "Meus Favoritos",
      game_cut_the_candy_title: "Cortar o Doce",
    game_cut_the_candy_desc: "Ajude o monstro a comer o doce! Corte as cordas, colete estrelas e evite obstáculos neste delicioso jogo de quebra-cabeça de física.",
    game_head_soccer_2026_title: "Futebol de Cabeça 2026",
    game_head_soccer_2026_desc: "Prepare-se para o torneio de futebol de cabeça mais importante de 2026. Chute, pule e marque gols para se tornar o campeão.",
    game_subway_riders_title: "Corredores do Metrô",
    game_subway_riders_desc: "Desvie de trens, corra o mais rápido que puder, colete moedas de ouro e escape do inspetor neste metrô sem fim.",
    exitGame: "Sair do jogo",
    liveSession: "Sessão ao vivo",
    playGame: "Jogar jogo",
    likeGame: "Curtir jogo",
    signInToLike: "Faça login para curtir",
    signInRequiredToLike: "É necessário fazer login para curtir os jogos!",
    backToGames: "Voltar para os jogos",
    plays: "jogadas",
    deviceCompatibilityText: "Celular, Tablet e Computador",
    about: "Sobre",
    playStation: "Estação de jogos",
    instantGameplayDesc: "Jogue instantaneamente em qualquer navegador de internet moderno.",
    myFavoriteGames: "Meus jogos favoritos",
    favoritesSubtitle: "Acesso rápido aos jogos H5 que você mais gosta de jogar.",
    emptyFavorites: "Sua lista está vazia",
    emptyFavoritesDesc: "Clique no ícone de coração em qualquer jogo para salvá-lo aqui.",
    signIn: "Entrar",
    myFavorites: "Meus Favoritos",
    logOut: "Sair",
    logIn: "Entrar",
    signUp: "Cadastrar-se",
    welcomeBack: "Bem-vindo de volta!",
    joinGamesato: "Junte-se ao Gamesato",
    loginDesc: "Faça login para carregar seus favoritos salvos, curtidas e estatísticas de jogo.",
    signupDesc: "Crie uma conta para salvar favoritos, curtir jogos e acompanhar suas estatísticas de jogo.",
    loginWithGoogle: "Entrar com Google",
    signupWithGoogle: "Cadastrar com Google",
    dontHaveAccount: "Não tem uma conta?",
    alreadyHaveAccount: "Já tem uma conta?",
    seoTitle: "Game Bite: Seu hub de jogos instantâneos",
    seoText1: "Experimente a próxima geração de jogos baseados na web com o Gamesato. Oferecemos uma seleção de jogos gratuitos de alta qualidade executados diretamente no seu navegador.",
    seoWhyChooseTitle: "Por que escolher o Game Bite?",
    seoWhyChoose1: "✓ Acesso instantâneo a mais de 1000 jogos premium",
    seoWhyChoose2: "✓ Sem downloads ou instalações necessárias",
    seoWhyChoose3: "✓ Ambiente seguro e livre de anúncios",
    seoMultiPlatformTitle: "Jogue em qualquer plataforma",
    seoMultiPlatformText: "Nossos jogos são otimizados para todos os navegadores modernos, garantindo sincronização perfeita do seu progresso.",
    faqTitle: "Perguntas frequentes",
    faq1Q: "Quais são os melhores jogos gratuitos no Gamesato?",
    faq1A: "Recomendamos começar com a nossa seção em Destaque. Nossos quebra-cabeças também são muito recomendados.",
    faq2Q: "Posso jogar jogos grátis sem instalar nada?",
    faq2A: "Sim, todos os jogos no Gamesato são jogos instantâneos em HTML5 executados diretamente no navegador.",
    faq3Q: "Preciso me registrar para jogar?",
    faq3A: "Não, o registro é totalmente opcional. Você pode jogar todos os jogos como convidado.",
      aboutTitle: "Sobre o Gamesato",
    aboutIntro: "Bem-vindo ao Gamesato! Seu destino definitivo para jogos web HTML5 H5 de alta qualidade e reprodução instantânea. Nossa missão é entregar uma experiência rápida, responsiva e envolvente diretamente no seu navegador, sem a necessidade de downloads, instalações ou logins.",
    aboutVisionTitle: "Nossa Visão Principal",
    aboutVisionText: "Acreditamos que jogar online deve ser livre de problemas. Otimizando os pacotes de arquivos de jogo e utilizando servidores modernos, entregamos jogos H5 à velocidade máxima, garantindo o divertimento imediato em qualquer celular, tablet ou computador.",
    aboutDevTitle: "Plataforma de Desenvolvedores",
    aboutDevText: "O Gamesato também apoia a comunidade de criadores de jogos. Oferecemos ferramentas para upload de jogos em arquivos ZIP, monitoramento de estatísticas em tempo real e avaliação segura do feedback de jogadores.",
    privacyTitle: "Política de Privacidade",
    privacyIntro: "No Gamesato, a privacidade de nossos visitantes é de extrema importância. Este documento descreve as informações coletadas e como as utilizamos para aprimorar sua experiência de jogo.",
    privacySec1Title: "1. Informações que Coletamos",
    privacySec1Text: "Ao criar sua conta através do Google, Facebook ou Discord, processamos e guardamos de forma segura dados como nome, e-mail e avatar do perfil apenas para personalização de sua lista de favoritos e curtidas.",
    privacySec2Title: "2. Estatísticas de Desempenho",
    privacySec2Text: "Para manter a velocidade do portal e selecionar os melhores jogos, rastreamos estatísticas de jogo anonimamente de forma agregada.",
    privacySec3Title: "3. Cookies e Armazenamento Local",
    privacySec3Text: "Utilizamos cookies e armazenamento local para gerenciar suas preferências e manter sua sessão iniciada com total segurança.",
    termsTitle: "Termos de Uso",
    termsIntro: "Bem-vindo ao Gamesato! Estes Termos de Uso regulam o acesso e utilização do nosso portal de jogos. Ao acessar nosso portal, você concorda com estes termos.",
    termsSec1Title: "1. Aceitação dos Termos",
    termsSec1Text: "Ao utilizar nosso site, assumimos que você concorda com estes termos. Não continue a usar o Gamesato se você não concordar com todas as condições descritas nesta página.",
    termsSec2Title: "2. Direitos Autorais e Licença",
    termsSec2Text: "Salvo indicação em contrário, o Gamesato e/ou seus licenciadores detêm os direitos autorais e propriedade intelectual de todas as mídias e jogos aqui presentes.",
    termsSec3Title: "3. Registro e Contas de Usuário",
    termsSec3Text: "O login por provedores OAuth compatíveis é necessário para salvar seus jogos favoritos e curtir novos títulos.",
    termsSec4Title: "4. Conduta dos Usuários",
    termsSec4Text: "Você concorda em usar os serviços apenas para entretenimento pessoal. Qualquer tentativa de hacker ou engenharia reversa do portal é expressamente proibida.",
    termsSec5Title: "5. Limitação de Responsabilidade",
    termsSec5Text: "Os serviços do Gamesato são disponibilizados 'como estão'. O Gamesato não se responsabiliza por eventuais perdas ou danos oriundos do uso do portal.",
  }
};

type LanguageKey = keyof typeof translations['en'];

interface LanguageState {
  language: string;
  setLanguage: (lang: string) => void;
  isMounted: boolean;
  setMounted: () => void;
}

export const useLanguageStore = create<LanguageState>((set) => ({
  language: 'en',
  isMounted: false,
  setLanguage: (lang) => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('appLanguage', lang);
    }
    set({ language: lang });
  },
  setMounted: () => set({ isMounted: true }),
}));

export function useTranslation() {
  const { language, setLanguage, isMounted, setMounted } = useLanguageStore();

  React.useEffect(() => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('appLanguage');
      if (stored && stored in translations) {
        setLanguage(stored);
      }
      setMounted();
    }
  }, [setLanguage, setMounted]);

  const t = (key: LanguageKey): string => {
    if (!isMounted) {
      return translations['en'][key];
    }
    const langDict = (translations[language as keyof typeof translations] || translations['en']) as Record<string, string>;
    return langDict[key as string] || translations['en'][key];
  };

  return { t, language, setLanguage };
}
